'''
Write a program to generate a Fibonacci series of numbers.
Starting numbers are 0 and 1,new number in the series is generated by adding previous two numbers in the series.
Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
b) Generate the series until the element in the series is less than Max number
'''


N=int(input('enter the range N: '))
t1=0
t2=1
print(t1,t2,end=' ')
for val in range(2,N):
    t3=t1+t2
    print(t3,end=' ')
    t1,t2=t2,t3

